[mypy]
mypy_path = .., ../x_make_common_x/shared_typings, ../x_make_common_x
explicit_package_bases = True

[mypy-PySide6.*]
ignore_missing_imports = True

[mypy-jsonschema.*]
ignore_missing_imports = True

[mypy-pytest]
ignore_missing_imports = True

[mypy-_pytest.*]
ignore_missing_imports = True



